### ISSUE TITLE
Unable to see Nvidia GPU in the lastest update

### ISSUE THREAD

**Issue by timidpigeon** [flathub/org.freedesktop.Platform.GL.nvidia#288] opened 2024-08-24 04:46 UTC
Using the latest update commit:
36de41e8ca7bfa79c42aaafb6e71fb276ca6a6d069c869a05b705a124b39b303
the Nvidia GPU doesn't show up.

Downgrading to b98fdca0728be9b1aa986b1569d4e15e79e26622fd3440e489feee9dda459afe fixes the issue.

**Comment by guihkx** [comment] 2024-08-24 04:58
Can you please explain exactly how you're testing this?

Also, please post the output of:

```
cat /sys/module/nvidia/version
```

And also:

```
flatpak info "org.freedesktop.Platform.GL.nvidia-$(cat /sys/module/nvidia/version | tr '.' '-')"
flatpak info "org.freedesktop.Platform.GL32.nvidia-$(cat /sys/module/nvidia/version | tr '.' '-')"
```

**Comment by Kimiblock** [comment] 2024-08-24 05:12
I'm on 560.31.02

```
cat /sys/module/nvidia/version
560.31.02
```

```
➜  ~ flatpak info "org.freedesktop.Platform.GL.nvidia-$(cat /sys/module/nvidia/version | tr '.' '-')"
     flatpak info "org.freedesktop.Platform.GL32.nvidia-$(cat /sys/module/nvidia/version | tr '.' '-')"
          ID: org.freedesktop.Platform.GL.nvidia-560-31-02
         Ref: runtime/org.freedesktop.Platform.GL.nvidia-560-31-02/x86_64/1.4
        Arch: x86_64
      Branch: 1.4
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2.1 MB

      Commit: ebade800744695a1cf864533e9abb64932d9f5c98c51c142dcac16d13bfc2d51
      Parent: 50f183eb62a71cb59d1bec3eafbd9cd637449adf754cc94b0fd9543692be052e
     Subject: Disable some more libarchive components (87bd7566)
        Date: 2024-08-23 22:58:08 +0000
          ID: org.freedesktop.Platform.GL32.nvidia-560-31-02
         Ref: runtime/org.freedesktop.Platform.GL32.nvidia-560-31-02/x86_64/1.4
        Arch: x86_64
      Branch: 1.4
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1.8 MB

      Commit: 8aeda55ed875fe045ee5627e624a25fb6014f310e72bc93e610030d2ff1c65d3
      Parent: 5d3ac7c07f7f319926f3f0f35c1ea630f65bd6442d83854b3b909f076a6a2071
     Subject: Disable some more libarchive components (87bd7566)
        Date: 2024-08-23 22:54:36 +0000
```

**Comment by dicksonleong** [comment] 2024-08-24 06:22
Same issue as well, none of the flatpak apps able to access the GPU for both 560.31.02 and 560.31.03.

Temporary workaround is to rollback to the previous flatpak driver:

1. rollback nvidia driver to 560.31.02 (depends on your distro)
2. update the flatpak driver to the previous commit:

    `sudo flatpak update --commit=50f183eb62a71cb59d1bec3eafbd9cd637449adf754cc94b0fd9543692be052e org.freedesktop.Platform.GL.nvidia-560-31-02/x86_64/1.4`

**Comment by Newbytee** [comment] 2024-08-24 07:09
Same here, Steam now shows my GPU as LLVMpipe:

![image](https://github.com/user-attachments/assets/b4d45e2d-5a27-4928-aaad-41f095b7786e)

This is with 555.58.02:
```
$ flatpak info org.freedesktop.Platform.GL.nvidia-555-58-02
          ID: org.freedesktop.Platform.GL.nvidia-555-58-02
         Ref: runtime/org.freedesktop.Platform.GL.nvidia-555-58-02/x86_64/1.4
        Arch: x86_64
      Branch: 1.4
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2,1 MB

      Commit: 36de41e8ca7bfa79c42aaafb6e71fb276ca6a6d069c869a05b705a124b39b303
      Parent: b98fdca0728be9b1aa986b1569d4e15e79e26622fd3440e489feee9dda459afe
     Subject: Disable some more libarchive components (87bd7566)
        Date: 2024-08-23 22:57:47 +0000
```

**Comment by dnet890** [comment] 2024-08-24 07:31
VLC also does not work

**Comment by XperiorTR** [comment] 2024-08-24 07:32
same issue, steam is reporting llvmpipe and stuff like org.vinegarhq.Sober just says "Cannot find Supported GPU"

**Comment by guihkx** [comment] 2024-08-24 07:33
Apologies, everyone. 

I found the root cause, and I'll open a PR with a fix soon.

**Comment by XperiorTR** [comment] 2024-08-24 07:33
oh god by the looks of the activity in this issue its widespread

**Comment by XperiorTR** [comment] 2024-08-24 07:33
> Apologies, everyone.
> 
> I found the root cause, and I'll open a PR with a fix soon.

pog

**Comment by seras42** [comment] 2024-08-24 07:33
Similar issue, anything trough flatpak that requires nvidia does not seem to work:

`cat /sys/module/nvidia/version
560.35.03
`

`flatpak info "org.freedesktop.Platform.GL.nvidia-$(cat /sys/module/nvidia/version | tr '.' '-')"
flatpak info "org.freedesktop.Platform.GL32.nvidia-$(cat /sys/module/nvidia/version | tr '.' '-')"
          ID: org.freedesktop.Platform.GL.nvidia-560-35-03
         Ref: runtime/org.freedesktop.Platform.GL.nvidia-560-35-03/x86_64/1.4
        Arch: x86_64
      Branch: 1.4
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 2,1 MB

      Commit: 95bd067590a86b5017bdf686c96d14a58e0f0ad0f42100af12a3489c78427d26
     Subject: Disable some more libarchive components (87bd7566)
        Date: 2024-08-23 22:43:10 +0000
          ID: org.freedesktop.Platform.GL32.nvidia-560-35-03
         Ref: runtime/org.freedesktop.Platform.GL32.nvidia-560-35-03/x86_64/1.4
        Arch: x86_64
      Branch: 1.4
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 1,8 MB

      Commit: 25d9cb627d52eaddb4e1bcfd612de042cea3a8b9f9ee4569a10068965870f14c
     Subject: Disable some more libarchive components (87bd7566)
        Date: 2024-08-23 22:45:51 +0000
`

**Comment by guihkx** [comment] 2024-08-24 07:50
Alright, the fix is in place, but unfortunately it will take some hours before it's finally available for everyone. 

I'll leave this open until that happens.

Thank you for your patience.

**Comment by CocolinoFan** [comment] 2024-08-24 10:16
Guy I'm not sure if I have the same issue. But it looks very similar. 
```
cat /sys/module/nvidia/version
535.183.01
```
```
flatpak info "org.freedesktop.Platform.GL.nvidia-$(cat /sys/module/nvidia/version | tr '.' '-')"
          ID: org.freedesktop.Platform.GL.nvidia-535-183-01
         Ref: runtime/org.freedesktop.Platform.GL.nvidia-535-183-01/x86_64/1.4
        Arch: x86_64
      Branch: 1.4
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2.1 MB

      Commit: 760156bc54db301eef95edd4ba2d1949f78967f5879ea74afdf25a71a2f5d246
      Parent: 1cdebbf15d2b48deeee697c9945a947ec0f9a572dc8e7e0e4c571c6782e93e14
     Subject: Add Vulkan 550.40.70 (4b830af0)
        Date: 2024-08-24 06:19:43 +0000

```
After an update today *some* flatpaks don't open for example:
```
flatpak run org.sdrangel.SDRangel
2024-08-24 09:47:46.549 (W) qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
2024-08-24 09:47:46.550 (W) qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
2024-08-24 09:47:46.550 (F) Could not initialize GLX
```
and
```
flatpak run org.kde.konsole
QColorSpace attempted constructed from invalid primaries: QPointF(0.313477,0.329102) QPointF(0.680664,0.320313) QPointF(0.265625,0.69043) QPointF(0.150391,0.0605469)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
```

I did run a `flatpak update` and updated:
```
Looking for updates…
        ID                                                        Branch             Op             Remote             Download
 1. [|] org.freedesktop.Platform.GL.nvidia-535-183-01
```
But even after a restart, the problem is still there.

**Comment by Dobsgw** [comment] 2024-08-24 10:30
@CocolinoFan your installed version is 1 commit behind - the latest version has not been built / uploaded yet

The latest commit fixes an issue: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/pull/289

Should be finished building fairly soon and we can test the new version.

**Comment by dnet890** [comment] 2024-08-24 11:36
<img width="549" alt="image" src="https://github.com/user-attachments/assets/ee47f03f-73f0-4fb2-8133-3f49d0ff5979">
new update is up. But, it does not worked

**Comment by Dobsgw** [comment] 2024-08-24 11:52
@dnet890 I'm not sure that's the latest version - the Subject should be "libzstd: Don't clean up files" to match the latest commit on github. I didn't receive the update yet though it has finished building and uploaded

**Comment by seras42** [comment] 2024-08-24 12:34
> <img alt="image" width="549" src="https://private-user-images.githubusercontent.com/29157187/361137183-ee47f03f-73f0-4fb2-8133-3f49d0ff5979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDIwMzUsIm5iZiI6MTcyNDUwMTczNSwicGF0aCI6Ii8yOTE1NzE4Ny8zNjExMzcxODMtZWU0N2YwM2YtNzNmMC00ZmIyLTgxMzMtM2Y0OWQwZmY1OTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDEyMTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiOTczY2EzZjNlZDQ5NWYxMWJjZjdlZTEzNTM5NWQ3NzY2MzAyODAwZGE5Y2E4ZTY5MzIxNjA1M2FhNjk0YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79RfHJIbhEAlUC_SPSD4HyxLla0pte8RXIHw16qA9So"> new update is up. But, it does not worked

Received the same update after the build finished, but its the older commit for the Add Vulkan (4b830af0). The newest one is (91727eb). I am wondering when can we expect the newest one? I am not familiar with flatpak update cycle.

**Comment by Inmoresentum** [comment] 2024-08-24 14:03
Every now and then something breaks :(

**Comment by rscm** [comment] 2024-08-24 14:03
I have the same issue

went down the rabbit hole and found the commits that work

```
$ sudo flatpak update --commit=e899b2cb2899d6b6cc20de30d68afb76123eb1d1818ea699709d15db12b99205 org.freedesktop.Platform.GL32.nvidia-555-58-02
$ sudo flatpak update --commit=729273848144d076550474e6070e4e84e92fac582582df53e19b71439c776a70 org.freedesktop.Platform.GL.nvidia-555-58-02
```

**Comment by Inmoresentum** [comment] 2024-08-24 14:05
Same here brother @rscm. Its sad to see that at the middle of a meeting slack broke :)

**Comment by iwanicki92** [comment] 2024-08-24 14:15
> went down the rabbit hole and found the commits that work

I can confirm, GPU-Viewer & Steam detects GPU now.

**Comment by guihkx** [comment] 2024-08-24 14:24
The fix is now live on Flathub, please run `flatpak update` to update!

**Closed by guihkx** 2024-08-24 14:24 UTC
