### ISSUE TITLE
Add 418.30 please

### ISSUE THREAD

**Issue by alex285** [flathub/org.freedesktop.Platform.GL.nvidia#8] opened 2019-02-13 15:23 UTC
thats a beta driver, but thats what Rawhide is using (RPM-Fusion), and in general people are trying NVIDIA betas, so it would be nice if we had Flatpak support, plus NVIDIA doesnt update that often

418.30: https://www.nvidia.com/download/driverResults.aspx/142166/en-us

**Comment by TingPing** [comment] 2019-02-13 15:50
Duplicate of #1

**Closed by TingPing** 2019-02-13 15:50 UTC
