### ISSUE TITLE
how to install org.freedesktop.Platform.GL32.nvidia ?

### ISSUE THREAD

**Issue by Hyphaed** [flathub/org.freedesktop.Platform.GL.nvidia#284] opened 2024-08-23 08:10 UTC
How I can get the org.freedesktop.Platform.GL32.nvidia package also?

flatpaks need this to run, not only the org.freedesktop.Platform.GL.nvidia

or is there a way to tell flatpaks to use always org.freedesktop.Platform.GL.nvidia and do not check for org.freedesktop.Platform.GL32.nvidia?

**Comment by guihkx** [comment] 2024-08-23 17:28
In short, it's not easy to build the GL32 package locally, because the old 1.6 i386 SDK we rely upon has been removed from Flathub and so we can't download it.

[This pull request](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/pull/234) aims to fix this issue, but other technical issues must be solved first before it gets merged.

And this is a essentially a duplicate of #282.

**Comment by TingPing** [comment] 2024-08-23 17:47
Flatpak automatically installs this, users don't have to do anything.

After a host driver update just run `flatpak update`.

**Comment by guihkx** [comment] 2024-08-24 01:05
I'm assuming the two answers above were enough to answer your question, so I'm closing this now.

Feel free to reopen if that's not the case.

**Closed by guihkx** 2024-08-24 01:05 UTC
